### ISSUE TITLE
npm installl problem

### ISSUE THREAD

**Issue by jhe10709** [andnils/measure#1]
Försöker att installera detta i en Docker miljö men för hela tiden detta problem:

```text
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN deprecated nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for jest@23.0.0-alpha.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'measure'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-19T09_52_31_246Z-debug.log
```

Är det någon som vet vad det kan vara?

**Comment by andnils** [comment]
Jag hade gjort `npm install --save-dev jest` och då fått en alfa-version (23.0.0-alpha.0).
Jag har nu committat en downgrade till 22.4.2. Testa om det fungerar bättre.

I övrigt så saknas det en del i Dockerfile innan den blir möjlig att deploya.
Vi behöver lägga till en postgres-server (eller lägger vi den i en egen Docker container?), samt eventuellt nginx för att serva statiska filer (js/css etc). Just nu är det _inte_ upplagt för att clojure-servern skall serva statiska filer. Vi får se hur vi vill gör där...

**Comment by jhe10709** [comment]
Tack för fixen, nu går det bra att installera alla dependencies.
