### ISSUE TITLE
Alpine images

### ISSUE THREAD

**Issue by jherrlin** [andnils/measure#11]
All of the images are using the `alpine` versions. This versions is very small and very minimal and goes not contains `bash` so there is no way of accessing them. I suggest we go for `alpine` versions in production but not in development.

https://github.com/nodejs/docker-node#nodealpine

**Comment by jherrlin** [comment]
There is a fix for this in: https://github.com/andnils/measure/pull/13

**Comment by andnils** [comment]
Didn't know that bash weren't included in alpine...fixed!
