### ISSUE TITLE
Migrate to a leiningen template

### ISSUE THREAD

**Issue by andnils** [andnils/measure#3]
Eftersom detta är ett projektskelett, så borde det kanske vara en lein template?

Tänk dig bara: en ljum sommarkväll, fåglarna kvittrar och du tänker: "nu skulle det sitta fint med ett clojure web projekt med postgresql och react+es6 i fronten".

Allt du behöver göra då är
`lein new göttans my-project`

**Comment by jherrlin** [comment]
Det vore ju super! 
Jag tycker det låter som en bra ide och att vi ska bygga en bra en!

**Comment by andnils** [comment]
Har börjat snickra på en leiningen template, men jag tänker att jag lägger upp den i ett eget repo.
