### ISSUE TITLE
We need CSS

### ISSUE THREAD

**Issue by andnils** [andnils/measure#4]
Minimal: just add one `style.css` and link it from `index.html`.

CSS-"framework"? E.g. pure-css, etc.

Any fancy stuff like sass/less?

**Comment by jherrlin** [comment]
I think SASS is nice and would like to have that!
Maybe add a new container with Rubys `compass`?

**Comment by jherrlin** [comment]
Maybe something like this? https://github.com/webpack-contrib/sass-loader
To me it make sense that the frontend tasks take care of that.

**Comment by andnils** [comment]
Agree! I was looking at less-loader myself...

**Comment by jherrlin** [comment]
A PR for doing SASS in development env is here #12

**Comment by andnils** [comment]
#12 is merged, so we can close this issue.
