### ISSUE TITLE
Postgres connection in Clojure

### ISSUE THREAD

**Issue by jherrlin** [andnils/measure#5]
Vart sätter vi user/password/databas i Clojure för att ansluta till Postgres.

Detta är lösen/user för Postgres
https://github.com/andnils/measure/blob/master/docker-compose.yml#L37-L39

**Comment by andnils** [comment]
Fixat i commit 64f43e3f9d.
Följande env.variables plockar systemet upp (alt. sätts i profiles.clj - men det behövs ju inte när man kör docker):
MEASURE_HTTP_PORT
MEASURE_DB_URL
MEASURE_DB_USER
MEASURE_DB_PASSWORD
